apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: otel-enabled-tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: otel-enabled-tanzu-java-web-app
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "21"
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/rabeyta/otel-enabled-tanzu-java-web-app
      ref:
        branch: main
